### ISSUE TITLE
Change license to Creative Commons Zero

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#196]
I would like to relicense the LOOT masterlists/repositories to be under the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/) (effectively submit them to the public domain). See https://github.com/loot/loot.github.io/issues/61 for more thoughts on this.

@SilentSpike, @WrinklyNinja, @egocarib, @Sharlikran, @Kaenguru-Knobel-Kette, @CptMcSplody, @verbetam, @TokcDK, @garthand, @William-Imm, @Loganbacca, @shadowslasher410, @pStyl3, @kuroko137, @icopp, @EssArrBee, @Chaossama, @jmarsh411, @Kinaga, @Artorp, @pncampbell, @silentdark, @umbertomarotta, @steamb23, @Arthmoor, @olmokramer (these are [all the contributors listed on GitHub](https://github.com/loot/skyrim/graphs/contributors)) if you agree with moving to this much more free license, please write a comment here confirming this.

<details>
<summary>Agreed LOOT contributors</summary>

- [x] @SilentSpike a.k.a. kymckay
- [x] @WrinklyNinja
- [x] @egocarib
- [x] @Sharlikran
- [x] @Freso
- [x] @Kaenguru-Knobel-Kette
- [x] @CptMcSplody
- [x] @TokcDK
- [x] @garthand
- [x] @William-Imm
- [x] @Loganbacca
- [x] @pStyl3
- [x] @icopp
- [x] @EssArrBee
- [x] @Chaossama
- [x] @jmarsh411
- [x] @Artorp
- [x] @pncampbell
- [x] @umbertomarotta
- [x] @steamb23
- [x] @Arthmoor
- [x] @olmokramer
- [x] @shadowslasher410
- [x] @Kinaga
- [x] @sibir-ine (in case it wasn't clear 😛 )
- [x] @DaCoolX 
- [x] @Infernio 
- [x] @Targuinius 
- [x] @ddbb07 
- [x] @verbetam
- [x] @Yoosk 
- [x] @Xahtax 
- [x] @silentdark
- [x] @Velgus
- [x] @Nebulous112
- [x] LuthienKess `<luthien_kess at yahoo.com>`
- [x] @ArtificialTruth
- [x] jdm `<ltfullert at gmail.com>`
- [x] @kuroko137 ([Nexus](https://www.nexusmods.com/users/2639692))
</details>

<details>
<summary>Agreed BOSS contributors not already mentioned</summary>

- [x] @deathssoul
- [x] @spaceoden
- [x] @ineedbettername
- [x] @Aellis-BOSS ([Nexus](https://www.nexusmods.com/users/65745))
- [x] @LotteryDiscountz ([Nexus](https://www.nexusmods.com/users/5757231))
- [x] @lucascomamala
- [x] desidemona `<desidemona at hotmail.com>`
- [x] Peste `<jp.hogberg at gmail.com>` ([Nexus](https://www.nexusmods.com/users/2018660))
- [x] scrapperrm `<scrapperrm at gmail.com>` ([Nexus](https://www.nexusmods.com/users/4626306))
- [x] ~~@ArkangelCorvus~~ Contributions have been [reworked or deleted](https://github.com/loot/skyrim/issues/196#issuecomment-903321589)
- [x] ~~@v111v111~~ Contributions have been [reworked or deleted](https://github.com/loot/skyrim/issues/196#issuecomment-903258336)
- [x] ~~Torrello` <torrello.boss at gmail.com>` ([Nexus](https://www.nexusmods.com/users/2018867))~~ Contributions have been [reworked or deleted](https://github.com/loot/skyrim/issues/196#issuecomment-907411636)
- [x] ~~Calen Ellefson `<tigercrab505 at gmail.com>` ([Nexus](https://www.nexusmods.com/users/3621086))~~ Clean-room reimplemented contributions
</details>

Remaining LOOT contributors:
- None, all done. 🏆 

Remaining BOSS contributors:
- None, all done. 🏆 

Once/if everyone accepts, I'll change the license.

**Comment by Freso** [comment]
@WrinklyNinja If you're able to get a list of BOSS contributors prior to the conversion that haven't been mentioned above, that'd be great. :)

**Comment by Chaossama** [comment]
I agree.

**Comment by Artorp** [comment]
I agree, go for it. 🙂

**Comment by pncampbell** [comment]
Agreed

**Comment by Arthmoor** [comment]
Could have sworn we already did this once before, but sure. I have no objections.

**Comment by umbertomarotta** [comment]
I agree

**Comment by MacSplody** [comment]
Yarp

**Comment by egocarib** [comment]
Agree

**Comment by Ortham** [comment]
> Could have sworn we already did this once before, but sure. I have no objections.

Same, but I think that was only for the Skyrim SE masterlist maybe?

**Comment by olmokramer** [comment]
Yea sure

**Comment by kymckay** [comment]
👍 I've ticked my box on all respective issues

**Comment by ProbablyManuel** [comment]
I agree

**Comment by Freso** [comment]
@SilentSpike @WrinklyNinja I know it's a bit of a bother and will cause some spam, but it would be great if you'd leave a comment on all the issues noting your approval, in addition to ticking your boxes. 🙈

**Comment by Ortham** [comment]
I agree.

**Comment by pStyl3** [comment]
Agreed.

**Comment by ElArGee** [comment]
Agreed.

**Comment by Sharlikran** [comment]
+1

**Comment by icopp** [comment]
+1

**Comment by jmarsh411** [comment]
Agree

**Comment by Freso** [comment]
@WrinklyNinja You didn't provide a list of old BOSS contributors for the Skyrim masterlist, is this because all of them also contributed to the LOOT one so they're already listed above… or did you just forget/miss it? :)

**Comment by Ortham** [comment]
I forgot about it, here they are:

- @LotteryDiscountz
- @Aellis-BOSS
- @lucascomamala
- @ineedbettername
- @ArkangelCorvus

People I couldn't match to GitHub accounts:

```
menduki <menduki@yandex.ru>
v111 <v111v111boss@gmail.com>
scrapperrm <scrapperrm@gmail.com>
Torrello <torrello.boss@gmail.com>
Peste <jp.hogberg@gmail.com>
Space Oden69 <jacksonleist@gmail.com>
Calen Ellefson <tigercrab505@gmail.com>
Psymon <simon888@cox.net>
SomeWelshGuy <joshthead@gmail.com>
deaths_soul (MCP) <NULL>
desidemona <desidemona@hotmail.com>
Zoe Alice Kahala <zoe.alice.kahala@gmail.com>
Chevenga <chevenga@gmail.com>
```

**Comment by deathssoul** [comment]
CC0 is fine by me for the metadata: https://github.com/loot/oblivion/issues/24#issuecomment-410244509

:)

**Comment by TokcDK** [comment]
<details>
  <summary>spoiler</summary>
  menduki@yandex.ru it is my email wich I used before tokcdk@gmail.com
</details>

**Comment by Freso** [comment]
@TokcDK And you agree with the change of license?

**Comment by TokcDK** [comment]
Yes, I agree.

**Comment by TokcDK** [comment]
<v111v111boss@gmail.com it is man which I invited and he made couple commits to BOSS\Skyrim or BOSS\Oblivion on Google. I didn have contacts with him many years latest mail was in 2014.

**Comment by Freso** [comment]
@spaceoden gave permission here: https://github.com/loot/loot.github.io/issues/61#issuecomment-410348382

**Comment by Freso** [comment]
@TokcDK Any chance you could leave a comment on the issues for the other masterlists stating your agreement to change the license there? :)

**Comment by Freso** [comment]
E-mail received from `<desidemona at hotmail.com>`:
> I, Heather Hatcher aka `desidemona@hotmail.com`, give you my full permission to change the license.

**Comment by WilliamImm** [comment]
I see no issues with it

**Comment by garthand** [comment]
I agree!

**Comment by pStyl3** [comment]
@verbetam 
@shadowslasher410 
@kuroko137 
@EssArrBee 
@Kinaga 
@silentdark 
@steamb23 
@fulert
@LotteryDiscountz
@Aellis-BOSS
@lucascomamala
@ineedbettername
@ArkangelCorvus

Sorry to ping you again, but if time permits, could you evaluate the above mentioned situation?
Thank you.

**Comment by EssArrBee** [comment]
+1

**Comment by steamb23** [comment]
I am no longer contributing to your project but I agree to change the license terms. :+1:

**Comment by pStyl3** [comment]
There's not much hope that we can get a response from everybody, but maybe from the following three people:
@kuroko137 
@shadowslasher410 
@silentdark 
Could you take a look at the opening post of this issue and decide, whether or not you agree?

**Comment by Infernio** [comment]
I'm fine with relicensing my contributions to all four masterlists (loot/skyrim, loot/oblivion, loot/fallout3 and loot/falloutnv).

**Comment by sibir-ine** [comment]
@shadowslasher410 agreed in https://github.com/loot/fallout4/issues/42#issuecomment-313950643 & stated that we should change the license for every masterlist, so I think we can take that as approval for this one.

**Comment by sibir-ine** [comment]
@Kinaga agreed in https://github.com/loot/skyrimse/issues/34#issuecomment-318321917, so I think we can take that as approval for this one.

**Comment by shadowslasher410** [comment]
Yep, I agree for all of them.

**Comment by sibir-ine** [comment]
> 
> 
> Yep, I agree for all of them.

@shadowslasher410 Awesome, thank you for confirming!

**Comment by DaCoolX** [comment]
I agree to a CC0 license change under all my past and future contributions of all Loot related projects.

**Comment by Targuinia** [comment]
Yeah, sure thing

**Comment by sibir-ine** [comment]
@verbetam @kuroko137 @silentdark @LotteryDiscountz @Aellis-BOSS @lucascomamala @ineedbettername @ArkangelCorvus @v111v111

If you guys are still around, could you please read this issue & state whether you agree?

**Comment by ineedbettername** [comment]
Yes, sorry for the delay, I agree to the license changes. 
-------- Original message --------From: sibir ***@***.***> Date: 4/11/21  10:31  (GMT-08:00) To: loot/skyrim ***@***.***> Cc: ineedbettername ***@***.***>, Mention ***@***.***> Subject: Re: [loot/skyrim]  Change license to Creative Commons Zero (#196) 
@verbetam @kuroko137 @silentdark @LotteryDiscountz @Aellis-BOSS @lucascomamala @ineedbettername @ArkangelCorvus
If you guys are still around, could you please read this issue & state whether you agree?

**Comment by sibir-ine** [comment]
@ineedbettername Awesome, thank you for replying!

**Comment by sibir-ine** [comment]
ddbb07 agreed in https://github.com/loot/oblivion/issues/24#issuecomment-817373341.

**Comment by sibir-ine** [comment]
@verbetam agreed via email:

> Email seems to be the more proper way to record my response. I give my consent to any license changes as desired. Thank you for reaching out and best of luck moving forward.

**Comment by sibir-ine** [comment]
Outstanding BOSS contributors' contributions:
- [v111v111](https://github.com/boss-developers/skyrim/commits/master?author=v111v111): 6 pages of commits
- [Torrello](https://github.com/boss-developers/skyrim/commits/master?author=torrello.boss@gmail.com): 2 pages of commits
- [ArkangelCorvus](https://github.com/boss-developers/skyrim/commits/master?author=ArkangelCorvus): 1 page of commits
- [Calen Ellefson](https://github.com/boss-developers/skyrim/commits/master?author=tigercrab505@gmail.com): 1 page of commits ([TODO](https://gist.github.com/sibir-ine/91e1104590488b893d1b41bbc1ea930f))
- ~~[LotteryDiscountz](https://github.com/boss-developers/skyrim/commits/master?author=LotteryDiscountz): 17 pages of commits~~ Agreed
- ~~[Aellis-BOSS](https://github.com/boss-developers/skyrim/commits/master?author=Aellis-BOSS): 10 pages of commits~~ Agreed
- ~~[scrapperrm](https://github.com/boss-developers/skyrim/commits/master?author=scrapperrm@gmail.com): 4 pages of commits~~ Agreed
- ~~[lucascomamala](https://github.com/boss-developers/skyrim/commits/master?author=lucascomamala): 2 pages of commits~~ Agreed
- ~~[Peste](https://github.com/boss-developers/skyrim/commits/master?author=jp.hogberg@gmail.com): 1 page of commits~~ Agreed
- ~~[SomeWelshGuy](https://github.com/boss-developers/skyrim/commits/master?author=joshthead@gmail.com): 3 commits~~ Changes no longer present, agreement not required
- ~~[Zoe Alice Kahala](https://github.com/boss-developers/skyrim/commits/master?author=zoe.alice.kahala@gmail.com): 2 commits~~ Changes no longer present, agreement not required
- ~~[Chevenga](https://github.com/boss-developers/skyrim/commits/master?author=chevenga@gmail.com): 1 commit~~ Changes no longer present, agreement not required

Outstanding LOOT contributors' contributions:
- ~~[kuroko137](https://github.com/loot/skyrim/commits/v0.15?author=kuroko137): 2 commits~~ (`ja` translations, many still exist & can't be easily replaced) - Agreed
- ~~[tomtesoro](https://github.com/loot/skyrim/commits/v0.15?author=tomtesoro): 1 commit~~ Changes no longer present, agreement not required

**Comment by sibir-ine** [comment]
SomeWelshGuy has one [change](https://github.com/boss-developers/skyrim/commit/1e742ad8a34000a0a09e9e7f6e3975de30f20847) still present:

https://github.com/loot/skyrim/blob/edfc6f51ea900a3f06771d391cf674fffff815b9/masterlist.yaml#L2187-L2188

`MagicDuel.esm` has been [hidden](https://www.nexusmods.com/skyrim/mods/18763/), so this entry can be removed.

**Comment by sibir-ine** [comment]
Calen Ellefson has one [change](https://github.com/boss-developers/skyrim/commit/2206331f0bd90a29df7a2992b54161fd2dac55d7) still present:

https://github.com/loot/skyrim/blob/edfc6f51ea900a3f06771d391cf674fffff815b9/masterlist.yaml#L6130
https://github.com/loot/skyrim/blob/edfc6f51ea900a3f06771d391cf674fffff815b9/masterlist.yaml#L6135-L6137

The [mod](https://www.nexusmods.com/skyrim/mods/8075/) is still around & the tags still apply.

**Comment by Yoosk** [comment]
Agreed

**Comment by Xahtax** [comment]
I agree

**Comment by pncampbell** [comment]
I agree

**Comment by sibir-ine** [comment]
@ArtificialTruth @Nebulous112 @Velgus

If you guys are still around, could you please read this issue & state whether you agree?

**Comment by Velgus** [comment]
I agree.

**Comment by Nebulous112** [comment]
I agree to the license change.

 - Nebulous112

**Comment by sibir-ine** [comment]
LuthienKess agreed via email:

> I agree with the license change for all my contributions.

**Comment by ArtificialTruth** [comment]
I agree 👍

**Comment by sibir-ine** [comment]
jdm agreed via email:
> Sorry I missed this before now, I don't have a github account. My own contribution was pretty miniscule but for what it's worth, I approve of the change.

**Comment by pStyl3** [comment]
@Aellis-BOSS has agreed via PM on Nexus.
>  You and the current LOOT team may do as you see necessary with any and all contributions I have made.

**Comment by pStyl3** [comment]
@LotteryDiscountz has agreed via PM on Nexus.

>Howdy! Thanks for reaching out! I am strongly in favor of licensing any and all works I am involved in, past, present and future, at CC0 whenever possible. You have my full permission for any relicensing. Signed: Diana S Hamilton
>  
> LD

Thanks once again for responding! Also thanks a lot @Pickysaurus for helping out. 😃

**Comment by sibir-ine** [comment]
> LotteryDiscountz: 17 pages of commits

Awesome, thank you so much LotteryDiscountz & Pickysaurus! That'll make relicensing this masterlist a looot more feasible 😄

**Comment by sibir-ine** [comment]
@ArkangelCorvus @kuroko137 @lucascomamala @v111v111

Hello! I wanted to try reaching out to you guys again, so, if you see this & have some time, could you please read this issue & state whether you agree?

**Comment by sibir-ine** [comment]
@lucascomamala agreed via email:

> Yes, I accept.

**Comment by sibir-ine** [comment]
Peste agreed via email:

> Yes I agee

**Comment by sibir-ine** [comment]
scrapperrm agreed via email:

> I accept

**Comment by pStyl3** [comment]
@kuroko137 has agreed via PM on Nexus.

> Hi, pStyl3. I'm sorry for the very late reply.
I do not claim any rights to my translation for LOOT and welcome you to relicense it to the Creative Commons Zero license. Please feel free to include it.
I hope my translation will be of some help to you.

Thanks a lot kuroko, and of course we highly appreciate your contributions! Cheers. 👍 🎉

**Comment by pStyl3** [comment]
I think I'm done with @v111v111's contributions, I've updated and deleted a lot and quite a few were already updated at some earlier point. I'm pretty sure that I've looked at every single one of his commits, and in the occasional case that I've opted to not change anything the commit was fine as is. So from my point of view we are good to go and can tick his checkbox.

**Comment by pStyl3** [comment]
The contributions from @ArkangelCorvus have been reworked, reevaluated or deleted as well. ✔️

**Comment by pStyl3** [comment]
Once the Bash Tags for [this](https://gist.github.com/sibir-ine/91e1104590488b893d1b41bbc1ea930f) mod are checked, we can tick Calen Ellefson's checkbox as well.

**Comment by pStyl3** [comment]
Torrello's checkbox ticked. ✔️

**Comment by pStyl3** [comment]
The license has been changed to CC0.
Thanks to everyone involved.
